"""Authoritative requirement registry.

Each entry maps a numbered SRS requirement identifier (e.g. ``1.3.2``) to
its title. The identifiers and titles below were extracted from the frozen
topic files in ``srs/topics/``. They are change-controlled data: they must
only be modified through the controlled change workflow (Topic 1 / Topic 27).
"""

from __future__ import annotations

from typing import Final

# Authoritative requirement IDs for the implemented SRS topics.
REQ_REGISTRY: Final[dict[str, dict[str, str]]] = {
    "1": {
        "1.0": "Reference and Validation Basis",
        "1.1": "Document Identity",
        "1.2": "Document Metadata",
        "1.3": "Versioning Structure",
        "1.3.1": "Version Numbering Rules",
        "1.3.2": "Version Increment Rules",
        "1.4": "Version Status",
        "1.5": "Change Control",
        "1.5.1": "Change Request",
        "1.5.2": "Change Impact Assessment",
        "1.5.3": "Change Approval",
        "1.6": "Approval and Governance",
        "1.6.1": "Approval Authority",
        "1.6.2": "Approval State",
        "1.7": "Version History",
        "1.8": "Document Integrity",
        "1.9": "Document Storage and Access",
        "1.10": "Document Review Cycle",
        "1.11": "Baseline Locking",
        "1.11.1": "Baseline Creation",
        "1.11.2": "Baseline Lock",
        "1.11.3": "Baseline Modification",
        "1.12": "Auditability",
    },
    "2": {
        "2.1": "Goal Statement",
        "2.2": "Mission Statement",
        "2.3": "Primary Objective",
        "2.3.1": "Primary Objective Definition",
        "2.3.2": "Secondary Objectives",
        "2.4": "Expected System Outcome",
        "2.5": "Goal Scope",
        "2.6": "Goal Constraints",
        "2.7": "Non-Negotiable Goal Conditions",
        "2.7.1": "Mandatory Conditions",
        "2.7.2": "Goal Violation Conditions",
        "2.8": "Goal Immutability",
        "2.8.1": "Immutable Goal Elements",
        "2.8.2": "Controlled Modification Exception",
        "2.9": "Goal Evaluation Criteria",
        "2.10": "Goal Success Metrics",
        "2.10.1": "Quantitative Success Metrics",
        "2.10.2": "Qualitative Success Metrics",
        "2.11": "Goal Alignment",
        "2.12": "Goal Conflict Resolution",
        "2.12.1": "Conflict Detection",
        "2.12.2": "Conflict Resolution Priority",
        "2.13": "Goal Deviation Detection",
        "2.14": "Goal Validation and Review",
        "2.15": "Goal Baseline and Approval",
    },
    "3": {
        "3.1": "Proof of Value Definition",
        "3.2": "PoV Objectives",
        "3.3": "PoV Success Definition",
        "3.3.1": "Functional Success",
        "3.3.2": "Technical Success",
        "3.3.3": "Outcome Success",
        "3.4": "PoV Scope",
        "3.5": "PoV Success Conditions",
        "3.5.1": "Minimum Success Thresholds",
        "3.5.2": "Release Blocking Conditions",
        "3.6": "Evaluation Criteria",
        "3.7": "Performance Metrics",
        "3.7.1": "Performance Metrics Definition",
        "3.7.2": "Performance Metric Thresholds",
        "3.7.3": "Reliability Metrics",
        "3.8": "Functional Validation",
        "3.9": "Technical Validation",
        "3.10": "System Reliability Validation",
        "3.11": "Agent Behaviour Validation",
        "3.12": "Output Quality Validation",
        "3.13": "Risk and Safety Validation",
        "3.14": "Real-World Scenario Validation",
        "3.15": "PoV Test Environment",
        "3.15.1": "Simulation Environment",
        "3.15.2": "Paper-Trading Environment",
        "3.16": "PoV Data",
        "3.17": "Acceptance Criteria",
        "3.17.1": "Functional Acceptance",
        "3.17.2": "Safety Acceptance",
        "3.18": "Failure Criteria",
        "3.18.1": "Critical Failure",
        "3.18.2": "Non-Critical Failure",
        "3.19": "Evidence and Documentation",
        "3.20": "PoV Review and Approval",
        "3.21": "PoV Completion Criteria",
        "3.21.1": "Completion Validation",
        "3.21.2": "Expansion Approval",
        "3.22": "PoV Baseline and Version Control",
        "3.23": "PoV Re-Evaluation Criteria",
        "3.24": "PoV Limitations and Constraints",
    },
    "4": {
        "4.1": "System Scope Definition",
        "4.2": "In-Scope Capabilities",
        "4.2.1": "Included Capabilities",
        "4.2.2": "Capability Limits",
        "4.3": "Out-of-Scope Capabilities",
        "4.3.1": "Explicitly Excluded Functions",
        "4.4": "Functional Boundaries",
        "4.5": "Technical Boundaries",
        "4.6": "Data Boundaries",
        "4.7": "Market and Geographic Boundaries",
        "4.7.1": "Geographic Scope",
        "4.7.2": "Market Scope",
        "4.7.3": "Currency Scope",
        "4.8": "Operational Boundaries",
        "4.9": "User Interaction Boundaries",
        "4.10": "Agent Authority Boundaries",
        "4.10.1": "Allowed Agent Authority",
        "4.10.2": "Prohibited Agent Authority",
        "4.11": "Sub-Agent Scope Boundaries",
        "4.12": "Input Boundaries",
        "4.13": "Output Boundaries",
        "4.14": "Decision-Making Boundaries",
        "4.15": "Execution and Action Boundaries",
        "4.15.1": "Simulation Actions",
        "4.15.2": "Live-Action Restrictions",
        "4.16": "Risk and Safety Boundaries",
        "4.17": "External System and API Boundaries",
        "4.18": "Resource and Infrastructure Boundaries",
        "4.19": "Scope Violation Detection",
        "4.20": "Boundary Enforcement",
        "4.21": "Scope Expansion Restriction",
        "4.21.1": "Expansion Trigger",
        "4.21.2": "Expansion Approval",
        "4.22": "Scope Change Control",
        "4.23": "Scope Validation and Review",
        "4.24": "Scope Freeze and Baseline",
        "4.25": "Scope Exceptions and Escalation",
        "4.25.1": "Exception Detection",
        "4.25.2": "Escalation Rules",
    },
    "5": {
        "5.1": "Core System Principles",
        "5.2": "Non-Negotiable Rules",
        "5.3": "Goal Immutability Principle",
        "5.3.1": "Immutable Goal Elements",
        "5.3.2": "Goal Change Prohibition",
        "5.4": "Specification Completeness Principle",
        "5.5": "Agent Determinism Principle",
        "5.6": "No-Assumption Principle",
        "5.7": "No Unauthorized Change Principle",
        "5.8": "Human Approval",
        "5.8.1": "Approval-Required Actions",
        "5.8.2": "Non-Approval Actions",
        "5.9": "Scope Compliance Principle",
        "5.10": "Safety First Principle",
        "5.11": "Risk Control Principles",
        "5.12": "Data Integrity Principles",
        "5.13": "Decision Integrity Principles",
        "5.14": "Transparency and Explainability Rules",
        "5.15": "Auditability Requirements",
        "5.16": "Traceability Requirements",
        "5.17": "Error Handling Principles",
        "5.18": "Failure and Recovery Rules",
        "5.19": "Blocked-State and Escalation Rules",
        "5.20": "Security and Access Principles",
        "5.21": "Agent-to-Agent Communication Rules",
        "5.22": "Sub-Agent Behaviour Constraints",
        "5.23": "Parallel Execution Rules",
        "5.24": "Conflict Resolution Rules",
        "5.25": "Self-Evaluation Rules",
        "5.26": "Self-Improvement Restrictions",
        "5.26.1": "Allowed Improvements",
        "5.26.2": "Prohibited Self-Modifications",
        "5.27": "Change Proposal and Approval Rules",
        "5.27.1": "Change Proposal",
        "5.27.2": "Impact Assessment",
        "5.27.3": "Approval Gate",
        "5.27.4": "Validation Before Adoption",
        "5.28": "System Consistency Rules",
        "5.29": "Rule Violation Detection",
        "5.30": "Rule Enforcement Mechanism",
        "5.31": "Exception Handling Rules",
        "5.31.1": "Exception Definition",
        "5.31.2": "Exception Handling",
        "5.32": "Principle Validation and Review",
        "5.33": "Baseline Lock and Controlled Modification",
        "5.33.1": "Baseline Creation",
        "5.33.2": "Baseline Protection",
        "5.34": "Governance of Principles",
    },
    "6": {
        "6.1": "Architecture Objectives",
        "6.2": "Architecture Principles",
        "6.3": "System Architecture Overview",
        "6.3.1": "Logical Architecture",
        "6.3.2": "Runtime Architecture",
        "6.4": "Core System Components",
        "6.5": "Agent Layer Architecture",
        "6.6": "Background Monitoring Layer",
        "6.7": "SRS Management Layer",
        "6.8": "Data Layer",
        "6.9": "Intelligence and Analysis Layer",
        "6.10": "Decision Layer",
        "6.11": "Risk and Safety Layer",
        "6.12": "Execution Layer",
        "6.13": "Monitoring and P&L Layer",
        "6.14": "Dashboard Layer",
        "6.15": "Notification Layer",
        "6.16": "External Systems and API Layer",
        "6.17": "Inter-Agent Communication",
        "6.17.1": "Communication Protocol",
        "6.17.2": "Message Contract",
        "6.18": "Component Interfaces",
        "6.18.1": "Interface Contract",
        "6.18.2": "Input/Output Contract",
        "6.19": "Data Flow Architecture",
        "6.19.1": "Data Flow",
        "6.19.2": "Data Ownership",
        "6.20": "Control Flow Architecture",
        "6.21": "Event and Message Flow",
        "6.21.1": "Event Definition",
        "6.21.2": "Event Routing",
        "6.22": "State Management",
        "6.22.1": "System States",
        "6.22.2": "State Transitions",
        "6.23": "Failure Isolation Architecture",
        "6.23.1": "Failure Isolation",
        "6.23.2": "Failure Propagation Prevention",
        "6.24": "Recovery Architecture",
        "6.25": "Scalability Architecture",
        "6.26": "Observability Architecture",
        "6.27": "Security Architecture",
        "6.28": "Architecture Constraints",
        "6.29": "Architecture Validation",
        "6.30": "Architecture Baseline and Change Control",
    },
    "7": {
        "7.1": "Technology Selection Principles",
        "7.1.1": "Selection Criteria",
        "7.1.2": "Rejection Criteria",
        "7.2": "Programming Language Requirements",
        "7.3": "Backend Technology",
        "7.4": "Frontend Technology",
        "7.5": "Database Technology",
        "7.6": "Data Processing Technologies",
        "7.7": "AI/LLM Technology",
        "7.7.1": "LLM Responsibilities",
        "7.7.2": "Non-LLM Deterministic Responsibilities",
        "7.8": "Agent Framework Requirements",
        "7.9": "API and Integration Technologies",
        "7.9.1": "API Requirements",
        "7.9.2": "Integration Constraints",
        "7.10": "Web Scraping and Data Acquisition Technologies",
        "7.12": "Backtesting Technologies",
        "7.13": "Paper Trading Infrastructure",
        "7.14": "Dashboard Technologies",
        "7.15": "Notification Technologies",
        "7.16": "Authentication and Authorization Technologies",
        "7.17": "Security and Secrets Management Technologies",
        "7.18": "Version Control and Repository Structure",
        "7.18.1": "Repository Structure",
        "7.18.2": "Branch Strategy",
        "7.19": "CI/CD Technology Requirements",
        "7.20": "Containerization and Environment Management",
        "7.21": "Cloud and Infrastructure Requirements",
        "7.22": "Local Development Environment",
        "7.23": "Testing Frameworks",
        "7.24": "Logging and Monitoring Technologies",
        "7.25": "Technology Compatibility Requirements",
        "7.26": "Dependency Management",
        "7.26.1": "Dependency Pinning",
        "7.26.2": "Dependency Update Rules",
        "7.28": "Cost and Resource Feasibility",
        "7.28.1": "Infrastructure Cost",
        "7.28.2": "API/Data Cost",
        "7.29": "Technical Risk Assessment",
        "7.29.1": "Technical Risks",
        "7.29.2": "Mitigation Requirements",
        "7.30": "Technology Selection Validation",
        "7.31": "Technology Baseline and Change Control",
    },
    "8": {
        "8.1": "Determinism Objectives",
        "8.2": "Specification Completeness Objectives",
        "8.3": "Explicit Instruction Requirements",
        "8.4": "Input Specification",
        "8.4.1": "Input Schema",
        "8.4.2": "Input Validation",
        "8.5": "Output Specification",
        "8.5.1": "Output Schema",
        "8.5.2": "Output Validation",
        "8.6": "Processing Rules",
        "8.6.1": "Processing Sequence",
        "8.7": "Decision Rules",
        "8.7.1": "Deterministic Rules",
        "8.7.2": "Rule Priority",
        "8.8": "Constraint Definition",
        "8.9": "Dependency Definition",
        "8.10": "Prerequisite Definition",
        "8.11": "Allowed Technology Definition",
        "8.12": "Tool Usage Rules",
        "8.13": "API Usage Rules",
        "8.14": "Data Source Requirements",
        "8.15": "Expected Behaviour Definition",
        "8.16": "Prohibited Behaviour Definition",
        "8.17": "No-Assumption Enforcement",
        "8.17.1": "Forbidden Assumptions",
        "8.18": "Ambiguity Detection",
        "8.18.1": "Ambiguity Detection",
        "8.18.2": "Ambiguity Resolution",
        "8.19": "Clarification Prevention Rules",
        "8.20": "Undefined-State Handling",
        "8.20.1": "Undefined State",
        "8.20.2": "Required Safe Behaviour",
        "8.21": "Blocked-State Handling",
        "8.21.1": "Blocked State",
        "8.21.2": "Escalation State",
        "8.22": "Agent Interpretation Validation",
        "8.23": "Requirement-to-Implementation Mapping",
        "8.24": "Acceptance Criteria Definition",
        "8.25": "Testability Requirements",
        "8.26": "Agent Self-Verification",
        "8.27": "Specification Consistency Checks",
        "8.28": "Cross-Agent Specification Consistency",
        "8.29": "Specification Completeness Validation",
        "8.30": "Determinism Validation",
        "8.31": "Specification Change Control",
    },
    "9": {
        "9.1": "Lifecycle Objectives",
        "9.2": "System Initialization",
        "9.2.1": "Startup Sequence",
        "9.2.2": "Startup Failure Handling",
        "9.3": "Environment Validation",
        "9.4": "SRS Loading and Verification",
        "9.5": "Goal Verification",
        "9.6": "Configuration Verification",
        "9.7": "Dependency Verification",
        "9.8": "Data Source Initialization",
        "9.9": "Agent Initialization",
        "9.10": "Sub-Agent Initialization",
        "9.11": "Task Assignment",
        "9.12": "Task Prioritization",
        "9.13": "Prerequisite Validation",
        "9.14": "Sequential Task Execution",
        "9.14.1": "Task Start",
        "9.14.2": "Task Completion",
        "9.15": "Parallel Task Execution",
        "9.15.1": "Parallelization Conditions",
        "9.15.2": "Parallelization Restrictions",
        "9.16": "Inter-Agent Coordination",
        "9.17": "Continuous Progress Tracking",
        "9.17.1": "Progress State",
        "9.17.2": "Progress Calculation",
        "9.18": "State Tracking",
        "9.19": "Real-Time Monitoring",
        "9.20": "Error Detection",
        "9.21": "Error Recovery",
        "9.22": "Blocked-State Management",
        "9.22.1": "Blocked-State Detection",
        "9.22.2": "Recovery and Escalation",
        "9.23": "Human Escalation",
        "9.24": "Output Validation",
        "9.25": "Self-Testing",
        "9.26": "Integration Validation",
        "9.27": "Completion Verification",
        "9.27.1": "Completion Conditions",
        "9.27.2": "Completion Validation",
        "9.28": "Deployment Readiness Check",
        "9.29": "Runtime Monitoring",
        "9.30": "Shutdown and Recovery",
        "9.31": "Lifecycle Audit Trail",
        "9.32": "Lifecycle Performance Metrics",
        "9.33": "Lifecycle Re-Evaluation",
        "9.34": "Lifecycle Change Control",
    },
    "10": {
        "10.1": "Data Acquisition Objectives",
        "10.2": "Data Source Identification",
        "10.3": "Approved Data Sources",
        "10.3.1": "Source Approval Criteria",
        "10.3.2": "Source Classification",
        "10.3.3": "Source Authority and Reliability",
        "10.3.4": "Licensing and Usage Restrictions",
        "10.3.5": "Source Replacement Rules",
        "10.4": "Market Data Sources",
        "10.5": "News Data Sources",
        "10.6": "Financial Data Sources",
        "10.7": "Economic Data Sources",
        "10.8": "Alternative Data Sources",
        "10.9": "Real-Time Data Requirements",
        "10.9.1": "Required Data Fields",
        "10.9.2": "Maximum Acceptable Latency",
        "10.10": "Historical Data Requirements",
        "10.11": "Data Source Authentication",
        "10.12": "API Integration",
        "10.13": "Web Data Acquisition",
        "10.14": "Data Scraping Rules",
        "10.15": "Data Retrieval Frequency",
        "10.15.1": "Retrieval Schedule",
        "10.15.2": "Event-Triggered Retrieval",
        "10.16": "Data Freshness Requirements",
        "10.17": "Data Rate Limits",
        "10.18": "Data Acquisition Failure Handling",
        "10.18.1": "Retry",
        "10.18.2": "Fallback Source",
        "10.18.3": "Failure Escalation",
        "10.19": "Source Redundancy",
        "10.19.1": "Primary Source",
        "10.19.2": "Secondary Source",
        "10.20": "Data Acquisition Logging",
        "10.21": "Data Provenance",
        "10.21.1": "Provenance Metadata",
        "10.21.2": "Source Traceability",
        "10.22": "Data Storage",
        "10.23": "Data Update Mechanism",
        "10.24": "Data Source Reliability Scoring",
        "10.25": "Data Acquisition Validation",
        "10.26": "Data Acquisition Security",
        "10.27": "Data Acquisition Cost Control",
        "10.28": "Data Source Change Detection",
        "10.29": "Data Acquisition Monitoring",
        "10.30": "Data Acquisition Baseline and Change Control",
    },
    "11": {
        "11.1": "Data Quality Objectives",
        "11.2": "Data Completeness",
        "11.2.1": "Completeness Rules",
        "11.2.2": "Missing-Field Thresholds",
        "11.3": "Data Accuracy",
        "11.3.1": "Accuracy Rules",
        "11.3.2": "Cross-Source Accuracy",
        "11.4": "Data Consistency",
        "11.5": "Data Freshness Validation",
        "11.6": "Data Integrity Validation",
        "11.7": "Duplicate Data Detection",
        "11.8": "Missing Data Detection",
        "11.9": "Invalid Data Detection",
        "11.10": "Anomaly Detection",
        "11.10.1": "Anomaly Detection Rules",
        "11.10.2": "Anomaly Severity",
        "11.11": "Outlier Detection",
        "11.12": "Source Cross-Validation",
        "11.12.1": "Cross-Source Matching",
        "11.12.2": "Conflict Resolution",
        "11.13": "Timestamp Validation",
        "11.14": "Market Data Validation",
        "11.15": "News Data Validation",
        "11.16": "Financial Data Validation",
        "11.17": "Data Normalization",
        "11.18": "Data Transformation",
        "11.19": "Data Reconciliation",
        "11.20": "Data Confidence Scoring",
        "11.20.1": "Confidence Calculation",
        "11.20.2": "Confidence Thresholds",
        "11.21": "Data Quality Thresholds",
        "11.22": "Invalid Data Handling",
        "11.22.1": "Reject",
        "11.22.2": "Quarantine",
        "11.22.3": "Recovery",
        "11.23": "Data Quarantine",
        "11.24": "Data Recovery",
        "11.25": "Data Quality Reporting",
        "11.26": "Data Quality Monitoring",
        "11.27": "Data Quality Audit Trail",
        "11.28": "Data Validation Testing",
        "11.29": "Data Quality Acceptance Criteria",
        "11.30": "Data Validation Baseline and Change Control",
    },
    "12": {
        "12.1": "Opportunity Discovery Objectives",
        "12.2": "Opportunity Definition",
        "12.3": "Market Scanning",
        "12.4": "Asset Universe Definition",
        "12.5": "Opportunity Identification",
        "12.5.1": "Detection Signals",
        "12.5.2": "Detection Conditions",
        "12.6": "Opportunity Filtering",
        "12.6.1": "Hard Filters",
        "12.6.2": "Soft Filters",
        "12.7": "Short-Term Opportunity Detection",
        "12.8": "Market Event Detection",
        "12.9": "News-Driven Opportunity Detection",
        "12.10": "Price-Movement Detection",
        "12.11": "Volume-Based Opportunity Detection",
        "12.12": "Volatility-Based Opportunity Detection",
        "12.13": "Liquidity Filtering",
        "12.14": "Opportunity Qualification",
        "12.14.1": "Qualification Criteria",
        "12.14.2": "Disqualification Criteria",
        "12.15": "Opportunity Ranking",
        "12.16": "Opportunity Deduplication",
        "12.17": "Opportunity Evidence Collection",
        "12.17.1": "Required Evidence",
        "12.17.2": "Evidence Freshness",
        "12.18": "Opportunity Confidence Score",
        "12.18.1": "Confidence Inputs",
        "12.18.2": "Confidence Threshold",
        "12.19": "Opportunity Expiry",
        "12.19.1": "Expiry Conditions",
        "12.19.2": "Expired Opportunity Handling",
        "12.20": "Opportunity Re-Evaluation",
        "12.21": "False Opportunity Detection",
        "12.21.1": "False Signal Detection",
        "12.21.2": "False Signal Classification",
        "12.22": "Opportunity Risk Pre-Filter",
        "12.23": "Opportunity Monitoring",
        "12.24": "Opportunity Discovery Testing",
        "12.25": "Opportunity Discovery Failure Handling",
        "12.26": "Opportunity Discovery Audit Trail",
        "12.27": "Opportunity Discovery Performance Metrics",
        "12.28": "Opportunity Discovery Validation",
        "12.29": "Opportunity Discovery Acceptance Criteria",
        "12.30": "Opportunity Discovery Change Control",
    },
    "13": {
        "13.1": "Market Analysis Objectives",
        "13.2": "Market Context Analysis",
        "13.3": "Market Trend Analysis",
        "13.4": "Price Analysis",
        "13.5": "Volume Analysis",
        "13.6": "Volatility Analysis",
        "13.7": "Liquidity Analysis",
        "13.8": "Technical Analysis",
        "13.8.1": "Indicator Inputs",
        "13.8.2": "Indicator Rules",
        "13.9": "Fundamental Analysis",
        "13.10": "News Analysis",
        "13.10.1": "News Relevance",
        "13.10.2": "News Impact",
        "13.11": "Sentiment Analysis",
        "13.11.1": "Sentiment Inputs",
        "13.11.2": "Sentiment Confidence",
        "13.12": "Event Analysis",
        "13.13": "Macro-Economic Context",
        "13.14": "Sector Analysis",
        "13.15": "Asset-Level Analysis",
        "13.16": "Short-Term Signal Analysis",
        "13.17": "Conflicting Signal Detection",
        "13.17.1": "Conflict Identification",
        "13.17.2": "Conflict Resolution",
        "13.18": "Signal Confidence Assessment",
        "13.18.1": "Confidence Calculation",
        "13.18.2": "Confidence Threshold",
        "13.19": "Market Regime Detection",
        "13.19.1": "Regime Classification",
        "13.19.2": "Regime Transition",
        "13.20": "Historical Context Comparison",
        "13.21": "Real-Time Re-Analysis",
        "13.21.1": "Re-Analysis Trigger",
        "13.21.2": "Re-Analysis Frequency",
        "13.22": "Analysis Evidence Requirements",
        "13.23": "Analysis Explainability",
        "13.24": "Analysis Error Handling",
        "13.25": "Analysis Validation",
        "13.26": "Analysis Testing",
        "13.27": "Analysis Performance Metrics",
        "13.28": "Analysis Audit Trail",
        "13.29": "Analysis Acceptance Criteria",
        "13.30": "Analysis Change Control",
    },
    "14": {
        "14.1": "Scoring Objectives",
        "14.2": "Scoring Framework",
        "14.2.1": "Scoring Inputs",
        "14.2.2": "Scoring Formula",
        "14.3": "Return Potential Score",
        "14.4": "Risk Score",
        "14.5": "Risk-Reward Score",
        "14.6": "Probability Score",
        "14.7": "Liquidity Score",
        "14.8": "Volatility Score",
        "14.9": "Time-to-Opportunity Score",
        "14.10": "Data Confidence Score",
        "14.11": "Market Condition Score",
        "14.12": "News Impact Score",
        "14.13": "Cost and Fee Score",
        "14.14": "Tax Impact Score",
        "14.15": "Capital Requirement Score",
        "14.16": "Composite Opportunity Score",
        "14.16.1": "Component Scores",
        "14.16.2": "Composite Calculation",
        "14.17": "Score Weighting",
        "14.17.1": "Weight Definition",
        "14.17.2": "Weight Validation",
        "14.18": "Score Thresholds",
        "14.18.1": "Minimum Score",
        "14.18.2": "Rejection Threshold",
        "14.19": "Opportunity Ranking",
        "14.20": "Score Explainability",
        "14.21": "Score Recalculation",
        "14.21.1": "Recalculation Trigger",
        "14.22": "Score Decay",
        "14.22.1": "Score Decay Rule",
        "14.22.2": "Expiry Threshold",
        "14.23": "Score Validation",
        "14.24": "Score Sensitivity Testing",
        "14.25": "Scoring Error Detection",
        "14.26": "Scoring Performance Metrics",
        "14.27": "Scoring Audit Trail",
        "14.28": "Scoring Acceptance Criteria",
        "14.29": "Scoring Testing",
        "14.30": "Scoring Change Control",
    },
}

# Authorized lifecycle statuses for controlled documents (Topic 1.4/1.6).
REQ_AUTHORIZED_STATUSES: Final[frozenset[str]] = frozenset(
    {
        "DRAFT",
        "IN_REVIEW",
        "APPROVED",
        "BASELINED",
        "SUPERSEDED",
        "REJECTED",
        "ARCHIVED",
    }
)


def get_requirement_title(topic: str, requirement_id: str) -> str:
    """Return the title for a numbered requirement ID.

    Args:
        topic: Topic number as a string (e.g. ``"1"``).
        requirement_id: Numbered requirement ID (e.g. ``"1.3.2"``).

    Returns:
        The registered title for the requirement.

    Raises:
        KeyError: If the topic or requirement ID is not registered.
    """
    if topic not in REQ_REGISTRY:
        raise KeyError(f"Topic {topic} is not registered in the requirements registry")
    if requirement_id not in REQ_REGISTRY[topic]:
        raise KeyError(f"Requirement {requirement_id} is not registered in topic {topic}")
    return REQ_REGISTRY[topic][requirement_id]
