"""Authoritative requirement registry.

Each entry maps a numbered SRS requirement identifier (e.g. ``1.3.2``) to
its title. The identifiers and titles below were extracted from the frozen
topic files in ``srs/topics/``. They are change-controlled data: they must
only be modified through the controlled change workflow (Topic 1 / Topic 27).
"""

from __future__ import annotations

from typing import Final

# Authoritative requirement IDs for the implemented SRS topics.
REQ_REGISTRY: Final[dict[str, dict[str, str]]] = {
    "1": {
        "1.0": "Reference and Validation Basis",
        "1.1": "Document Identity",
        "1.2": "Document Metadata",
        "1.3": "Versioning Structure",
        "1.3.1": "Version Numbering Rules",
        "1.3.2": "Version Increment Rules",
        "1.4": "Version Status",
        "1.5": "Change Control",
        "1.5.1": "Change Request",
        "1.5.2": "Change Impact Assessment",
        "1.5.3": "Change Approval",
        "1.6": "Approval and Governance",
        "1.6.1": "Approval Authority",
        "1.6.2": "Approval State",
        "1.7": "Version History",
        "1.8": "Document Integrity",
        "1.9": "Document Storage and Access",
        "1.10": "Document Review Cycle",
        "1.11": "Baseline Locking",
        "1.11.1": "Baseline Creation",
        "1.11.2": "Baseline Lock",
        "1.11.3": "Baseline Modification",
        "1.12": "Auditability",
    },
    "2": {
        "2.1": "Goal Statement",
        "2.2": "Mission Statement",
        "2.3": "Primary Objective",
        "2.3.1": "Primary Objective Definition",
        "2.3.2": "Secondary Objectives",
        "2.4": "Expected System Outcome",
        "2.5": "Goal Scope",
        "2.6": "Goal Constraints",
        "2.7": "Non-Negotiable Goal Conditions",
        "2.7.1": "Mandatory Conditions",
        "2.7.2": "Goal Violation Conditions",
        "2.8": "Goal Immutability",
        "2.8.1": "Immutable Goal Elements",
        "2.8.2": "Controlled Modification Exception",
        "2.9": "Goal Evaluation Criteria",
        "2.10": "Goal Success Metrics",
        "2.10.1": "Quantitative Success Metrics",
        "2.10.2": "Qualitative Success Metrics",
        "2.11": "Goal Alignment",
        "2.12": "Goal Conflict Resolution",
        "2.12.1": "Conflict Detection",
        "2.12.2": "Conflict Resolution Priority",
        "2.13": "Goal Deviation Detection",
        "2.14": "Goal Validation and Review",
        "2.15": "Goal Baseline and Approval",
    },
    "3": {
        "3.1": "Proof of Value Definition",
        "3.2": "PoV Objectives",
        "3.3": "PoV Success Definition",
        "3.3.1": "Functional Success",
        "3.3.2": "Technical Success",
        "3.3.3": "Outcome Success",
        "3.4": "PoV Scope",
        "3.5": "PoV Success Conditions",
        "3.5.1": "Minimum Success Thresholds",
        "3.5.2": "Release Blocking Conditions",
        "3.6": "Evaluation Criteria",
        "3.7": "Performance Metrics",
        "3.7.1": "Performance Metrics Definition",
        "3.7.2": "Performance Metric Thresholds",
        "3.7.3": "Reliability Metrics",
        "3.8": "Functional Validation",
        "3.9": "Technical Validation",
        "3.10": "System Reliability Validation",
        "3.11": "Agent Behaviour Validation",
        "3.12": "Output Quality Validation",
        "3.13": "Risk and Safety Validation",
        "3.14": "Real-World Scenario Validation",
        "3.15": "PoV Test Environment",
        "3.15.1": "Simulation Environment",
        "3.15.2": "Paper-Trading Environment",
        "3.16": "PoV Data",
        "3.17": "Acceptance Criteria",
        "3.17.1": "Functional Acceptance",
        "3.17.2": "Safety Acceptance",
        "3.18": "Failure Criteria",
        "3.18.1": "Critical Failure",
        "3.18.2": "Non-Critical Failure",
        "3.19": "Evidence and Documentation",
        "3.20": "PoV Review and Approval",
        "3.21": "PoV Completion Criteria",
        "3.21.1": "Completion Validation",
        "3.21.2": "Expansion Approval",
        "3.22": "PoV Baseline and Version Control",
        "3.23": "PoV Re-Evaluation Criteria",
        "3.24": "PoV Limitations and Constraints",
    },
    "4": {
        "4.1": "System Scope Definition",
        "4.2": "In-Scope Capabilities",
        "4.2.1": "Included Capabilities",
        "4.2.2": "Capability Limits",
        "4.3": "Out-of-Scope Capabilities",
        "4.3.1": "Explicitly Excluded Functions",
        "4.4": "Functional Boundaries",
        "4.5": "Technical Boundaries",
        "4.6": "Data Boundaries",
        "4.7": "Market and Geographic Boundaries",
        "4.7.1": "Geographic Scope",
        "4.7.2": "Market Scope",
        "4.7.3": "Currency Scope",
        "4.8": "Operational Boundaries",
        "4.9": "User Interaction Boundaries",
        "4.10": "Agent Authority Boundaries",
        "4.10.1": "Allowed Agent Authority",
        "4.10.2": "Prohibited Agent Authority",
        "4.11": "Sub-Agent Scope Boundaries",
        "4.12": "Input Boundaries",
        "4.13": "Output Boundaries",
        "4.14": "Decision-Making Boundaries",
        "4.15": "Execution and Action Boundaries",
        "4.15.1": "Simulation Actions",
        "4.15.2": "Live-Action Restrictions",
        "4.16": "Risk and Safety Boundaries",
        "4.17": "External System and API Boundaries",
        "4.18": "Resource and Infrastructure Boundaries",
        "4.19": "Scope Violation Detection",
        "4.20": "Boundary Enforcement",
        "4.21": "Scope Expansion Restriction",
        "4.21.1": "Expansion Trigger",
        "4.21.2": "Expansion Approval",
        "4.22": "Scope Change Control",
        "4.23": "Scope Validation and Review",
        "4.24": "Scope Freeze and Baseline",
        "4.25": "Scope Exceptions and Escalation",
        "4.25.1": "Exception Detection",
        "4.25.2": "Escalation Rules",
    },
    "5": {
        "5.1": "Core System Principles",
        "5.2": "Non-Negotiable Rules",
        "5.3": "Goal Immutability Principle",
        "5.3.1": "Immutable Goal Elements",
        "5.3.2": "Goal Change Prohibition",
        "5.4": "Specification Completeness Principle",
        "5.5": "Agent Determinism Principle",
        "5.6": "No-Assumption Principle",
        "5.7": "No Unauthorized Change Principle",
        "5.8": "Human Approval",
        "5.8.1": "Approval-Required Actions",
        "5.8.2": "Non-Approval Actions",
        "5.9": "Scope Compliance Principle",
        "5.10": "Safety First Principle",
        "5.11": "Risk Control Principles",
        "5.12": "Data Integrity Principles",
        "5.13": "Decision Integrity Principles",
        "5.14": "Transparency and Explainability Rules",
        "5.15": "Auditability Requirements",
        "5.16": "Traceability Requirements",
        "5.17": "Error Handling Principles",
        "5.18": "Failure and Recovery Rules",
        "5.19": "Blocked-State and Escalation Rules",
        "5.20": "Security and Access Principles",
        "5.21": "Agent-to-Agent Communication Rules",
        "5.22": "Sub-Agent Behaviour Constraints",
        "5.23": "Parallel Execution Rules",
        "5.24": "Conflict Resolution Rules",
        "5.25": "Self-Evaluation Rules",
        "5.26": "Self-Improvement Restrictions",
        "5.26.1": "Allowed Improvements",
        "5.26.2": "Prohibited Self-Modifications",
        "5.27": "Change Proposal and Approval Rules",
        "5.27.1": "Change Proposal",
        "5.27.2": "Impact Assessment",
        "5.27.3": "Approval Gate",
        "5.27.4": "Validation Before Adoption",
        "5.28": "System Consistency Rules",
        "5.29": "Rule Violation Detection",
        "5.30": "Rule Enforcement Mechanism",
        "5.31": "Exception Handling Rules",
        "5.31.1": "Exception Definition",
        "5.31.2": "Exception Handling",
        "5.32": "Principle Validation and Review",
        "5.33": "Baseline Lock and Controlled Modification",
        "5.33.1": "Baseline Creation",
        "5.33.2": "Baseline Protection",
        "5.34": "Governance of Principles",
    },
    "6": {
        "6.1": "Architecture Objectives",
        "6.2": "Architecture Principles",
        "6.3": "System Architecture Overview",
        "6.3.1": "Logical Architecture",
        "6.3.2": "Runtime Architecture",
        "6.4": "Core System Components",
        "6.5": "Agent Layer Architecture",
        "6.6": "Background Monitoring Layer",
        "6.7": "SRS Management Layer",
        "6.8": "Data Layer",
        "6.9": "Intelligence and Analysis Layer",
        "6.10": "Decision Layer",
        "6.11": "Risk and Safety Layer",
        "6.12": "Execution Layer",
        "6.13": "Monitoring and P&L Layer",
        "6.14": "Dashboard Layer",
        "6.15": "Notification Layer",
        "6.16": "External Systems and API Layer",
        "6.17": "Inter-Agent Communication",
        "6.17.1": "Communication Protocol",
        "6.17.2": "Message Contract",
        "6.18": "Component Interfaces",
        "6.18.1": "Interface Contract",
        "6.18.2": "Input/Output Contract",
        "6.19": "Data Flow Architecture",
        "6.19.1": "Data Flow",
        "6.19.2": "Data Ownership",
        "6.20": "Control Flow Architecture",
        "6.21": "Event and Message Flow",
        "6.21.1": "Event Definition",
        "6.21.2": "Event Routing",
        "6.22": "State Management",
        "6.22.1": "System States",
        "6.22.2": "State Transitions",
        "6.23": "Failure Isolation Architecture",
        "6.23.1": "Failure Isolation",
        "6.23.2": "Failure Propagation Prevention",
        "6.24": "Recovery Architecture",
        "6.25": "Scalability Architecture",
        "6.26": "Observability Architecture",
        "6.27": "Security Architecture",
        "6.28": "Architecture Constraints",
        "6.29": "Architecture Validation",
        "6.30": "Architecture Baseline and Change Control",
    },
    "7": {
        "7.1": "Technology Selection Principles",
        "7.1.1": "Selection Criteria",
        "7.1.2": "Rejection Criteria",
        "7.2": "Programming Language Requirements",
        "7.3": "Backend Technology",
        "7.4": "Frontend Technology",
        "7.5": "Database Technology",
        "7.6": "Data Processing Technologies",
        "7.7": "AI/LLM Technology",
        "7.7.1": "LLM Responsibilities",
        "7.7.2": "Non-LLM Deterministic Responsibilities",
        "7.8": "Agent Framework Requirements",
        "7.9": "API and Integration Technologies",
        "7.9.1": "API Requirements",
        "7.9.2": "Integration Constraints",
        "7.10": "Web Scraping and Data Acquisition Technologies",
        "7.12": "Backtesting Technologies",
        "7.13": "Paper Trading Infrastructure",
        "7.14": "Dashboard Technologies",
        "7.15": "Notification Technologies",
        "7.16": "Authentication and Authorization Technologies",
        "7.17": "Security and Secrets Management Technologies",
        "7.18": "Version Control and Repository Structure",
        "7.18.1": "Repository Structure",
        "7.18.2": "Branch Strategy",
        "7.19": "CI/CD Technology Requirements",
        "7.20": "Containerization and Environment Management",
        "7.21": "Cloud and Infrastructure Requirements",
        "7.22": "Local Development Environment",
        "7.23": "Testing Frameworks",
        "7.24": "Logging and Monitoring Technologies",
        "7.25": "Technology Compatibility Requirements",
        "7.26": "Dependency Management",
        "7.26.1": "Dependency Pinning",
        "7.26.2": "Dependency Update Rules",
        "7.28": "Cost and Resource Feasibility",
        "7.28.1": "Infrastructure Cost",
        "7.28.2": "API/Data Cost",
        "7.29": "Technical Risk Assessment",
        "7.29.1": "Technical Risks",
        "7.29.2": "Mitigation Requirements",
        "7.30": "Technology Selection Validation",
        "7.31": "Technology Baseline and Change Control",
    },
    "8": {
        "8.1": "Determinism Objectives",
        "8.2": "Specification Completeness Objectives",
        "8.3": "Explicit Instruction Requirements",
        "8.4": "Input Specification",
        "8.4.1": "Input Schema",
        "8.4.2": "Input Validation",
        "8.5": "Output Specification",
        "8.5.1": "Output Schema",
        "8.5.2": "Output Validation",
        "8.6": "Processing Rules",
        "8.6.1": "Processing Sequence",
        "8.7": "Decision Rules",
        "8.7.1": "Deterministic Rules",
        "8.7.2": "Rule Priority",
        "8.8": "Constraint Definition",
        "8.9": "Dependency Definition",
        "8.10": "Prerequisite Definition",
        "8.11": "Allowed Technology Definition",
        "8.12": "Tool Usage Rules",
        "8.13": "API Usage Rules",
        "8.14": "Data Source Requirements",
        "8.15": "Expected Behaviour Definition",
        "8.16": "Prohibited Behaviour Definition",
        "8.17": "No-Assumption Enforcement",
        "8.17.1": "Forbidden Assumptions",
        "8.18": "Ambiguity Detection",
        "8.18.1": "Ambiguity Detection",
        "8.18.2": "Ambiguity Resolution",
        "8.19": "Clarification Prevention Rules",
        "8.20": "Undefined-State Handling",
        "8.20.1": "Undefined State",
        "8.20.2": "Required Safe Behaviour",
        "8.21": "Blocked-State Handling",
        "8.21.1": "Blocked State",
        "8.21.2": "Escalation State",
        "8.22": "Agent Interpretation Validation",
        "8.23": "Requirement-to-Implementation Mapping",
        "8.24": "Acceptance Criteria Definition",
        "8.25": "Testability Requirements",
        "8.26": "Agent Self-Verification",
        "8.27": "Specification Consistency Checks",
        "8.28": "Cross-Agent Specification Consistency",
        "8.29": "Specification Completeness Validation",
        "8.30": "Determinism Validation",
        "8.31": "Specification Change Control",
    },
    "9": {
        "9.1": "Lifecycle Objectives",
        "9.2": "System Initialization",
        "9.2.1": "Startup Sequence",
        "9.2.2": "Startup Failure Handling",
        "9.3": "Environment Validation",
        "9.4": "SRS Loading and Verification",
        "9.5": "Goal Verification",
        "9.6": "Configuration Verification",
        "9.7": "Dependency Verification",
        "9.8": "Data Source Initialization",
        "9.9": "Agent Initialization",
        "9.10": "Sub-Agent Initialization",
        "9.11": "Task Assignment",
        "9.12": "Task Prioritization",
        "9.13": "Prerequisite Validation",
        "9.14": "Sequential Task Execution",
        "9.14.1": "Task Start",
        "9.14.2": "Task Completion",
        "9.15": "Parallel Task Execution",
        "9.15.1": "Parallelization Conditions",
        "9.15.2": "Parallelization Restrictions",
        "9.16": "Inter-Agent Coordination",
        "9.17": "Continuous Progress Tracking",
        "9.17.1": "Progress State",
        "9.17.2": "Progress Calculation",
        "9.18": "State Tracking",
        "9.19": "Real-Time Monitoring",
        "9.20": "Error Detection",
        "9.21": "Error Recovery",
        "9.22": "Blocked-State Management",
        "9.22.1": "Blocked-State Detection",
        "9.22.2": "Recovery and Escalation",
        "9.23": "Human Escalation",
        "9.24": "Output Validation",
        "9.25": "Self-Testing",
        "9.26": "Integration Validation",
        "9.27": "Completion Verification",
        "9.27.1": "Completion Conditions",
        "9.27.2": "Completion Validation",
        "9.28": "Deployment Readiness Check",
        "9.29": "Runtime Monitoring",
        "9.30": "Shutdown and Recovery",
        "9.31": "Lifecycle Audit Trail",
        "9.32": "Lifecycle Performance Metrics",
        "9.33": "Lifecycle Re-Evaluation",
        "9.34": "Lifecycle Change Control",
    },
    "10": {
        "10.1": "Data Acquisition Objectives",
        "10.2": "Data Source Identification",
        "10.3": "Approved Data Sources",
        "10.3.1": "Source Approval Criteria",
        "10.3.2": "Source Classification",
        "10.3.3": "Source Authority and Reliability",
        "10.3.4": "Licensing and Usage Restrictions",
        "10.3.5": "Source Replacement Rules",
        "10.4": "Market Data Sources",
        "10.5": "News Data Sources",
        "10.6": "Financial Data Sources",
        "10.7": "Economic Data Sources",
        "10.8": "Alternative Data Sources",
        "10.9": "Real-Time Data Requirements",
        "10.9.1": "Required Data Fields",
        "10.9.2": "Maximum Acceptable Latency",
        "10.10": "Historical Data Requirements",
        "10.11": "Data Source Authentication",
        "10.12": "API Integration",
        "10.13": "Web Data Acquisition",
        "10.14": "Data Scraping Rules",
        "10.15": "Data Retrieval Frequency",
        "10.15.1": "Retrieval Schedule",
        "10.15.2": "Event-Triggered Retrieval",
        "10.16": "Data Freshness Requirements",
        "10.17": "Data Rate Limits",
        "10.18": "Data Acquisition Failure Handling",
        "10.18.1": "Retry",
        "10.18.2": "Fallback Source",
        "10.18.3": "Failure Escalation",
        "10.19": "Source Redundancy",
        "10.19.1": "Primary Source",
        "10.19.2": "Secondary Source",
        "10.20": "Data Acquisition Logging",
        "10.21": "Data Provenance",
        "10.21.1": "Provenance Metadata",
        "10.21.2": "Source Traceability",
        "10.22": "Data Storage",
        "10.23": "Data Update Mechanism",
        "10.24": "Data Source Reliability Scoring",
        "10.25": "Data Acquisition Validation",
        "10.26": "Data Acquisition Security",
        "10.27": "Data Acquisition Cost Control",
        "10.28": "Data Source Change Detection",
        "10.29": "Data Acquisition Monitoring",
        "10.30": "Data Acquisition Baseline and Change Control",
    },
    "11": {
        "11.1": "Data Quality Objectives",
        "11.2": "Data Completeness",
        "11.2.1": "Completeness Rules",
        "11.2.2": "Missing-Field Thresholds",
        "11.3": "Data Accuracy",
        "11.3.1": "Accuracy Rules",
        "11.3.2": "Cross-Source Accuracy",
        "11.4": "Data Consistency",
        "11.5": "Data Freshness Validation",
        "11.6": "Data Integrity Validation",
        "11.7": "Duplicate Data Detection",
        "11.8": "Missing Data Detection",
        "11.9": "Invalid Data Detection",
        "11.10": "Anomaly Detection",
        "11.10.1": "Anomaly Detection Rules",
        "11.10.2": "Anomaly Severity",
        "11.11": "Outlier Detection",
        "11.12": "Source Cross-Validation",
        "11.12.1": "Cross-Source Matching",
        "11.12.2": "Conflict Resolution",
        "11.13": "Timestamp Validation",
        "11.14": "Market Data Validation",
        "11.15": "News Data Validation",
        "11.16": "Financial Data Validation",
        "11.17": "Data Normalization",
        "11.18": "Data Transformation",
        "11.19": "Data Reconciliation",
        "11.20": "Data Confidence Scoring",
        "11.20.1": "Confidence Calculation",
        "11.20.2": "Confidence Thresholds",
        "11.21": "Data Quality Thresholds",
        "11.22": "Invalid Data Handling",
        "11.22.1": "Reject",
        "11.22.2": "Quarantine",
        "11.22.3": "Recovery",
        "11.23": "Data Quarantine",
        "11.24": "Data Recovery",
        "11.25": "Data Quality Reporting",
        "11.26": "Data Quality Monitoring",
        "11.27": "Data Quality Audit Trail",
        "11.28": "Data Validation Testing",
        "11.29": "Data Quality Acceptance Criteria",
        "11.30": "Data Validation Baseline and Change Control",
    },
    "12": {
        "12.1": "Opportunity Discovery Objectives",
        "12.2": "Opportunity Definition",
        "12.3": "Market Scanning",
        "12.4": "Asset Universe Definition",
        "12.5": "Opportunity Identification",
        "12.5.1": "Detection Signals",
        "12.5.2": "Detection Conditions",
        "12.6": "Opportunity Filtering",
        "12.6.1": "Hard Filters",
        "12.6.2": "Soft Filters",
        "12.7": "Short-Term Opportunity Detection",
        "12.8": "Market Event Detection",
        "12.9": "News-Driven Opportunity Detection",
        "12.10": "Price-Movement Detection",
        "12.11": "Volume-Based Opportunity Detection",
        "12.12": "Volatility-Based Opportunity Detection",
        "12.13": "Liquidity Filtering",
        "12.14": "Opportunity Qualification",
        "12.14.1": "Qualification Criteria",
        "12.14.2": "Disqualification Criteria",
        "12.15": "Opportunity Ranking",
        "12.16": "Opportunity Deduplication",
        "12.17": "Opportunity Evidence Collection",
        "12.17.1": "Required Evidence",
        "12.17.2": "Evidence Freshness",
        "12.18": "Opportunity Confidence Score",
        "12.18.1": "Confidence Inputs",
        "12.18.2": "Confidence Threshold",
        "12.19": "Opportunity Expiry",
        "12.19.1": "Expiry Conditions",
        "12.19.2": "Expired Opportunity Handling",
        "12.20": "Opportunity Re-Evaluation",
        "12.21": "False Opportunity Detection",
        "12.21.1": "False Signal Detection",
        "12.21.2": "False Signal Classification",
        "12.22": "Opportunity Risk Pre-Filter",
        "12.23": "Opportunity Monitoring",
        "12.24": "Opportunity Discovery Testing",
        "12.25": "Opportunity Discovery Failure Handling",
        "12.26": "Opportunity Discovery Audit Trail",
        "12.27": "Opportunity Discovery Performance Metrics",
        "12.28": "Opportunity Discovery Validation",
        "12.29": "Opportunity Discovery Acceptance Criteria",
        "12.30": "Opportunity Discovery Change Control",
    },
    "13": {
        "13.1": "Market Analysis Objectives",
        "13.2": "Market Context Analysis",
        "13.3": "Market Trend Analysis",
        "13.4": "Price Analysis",
        "13.5": "Volume Analysis",
        "13.6": "Volatility Analysis",
        "13.7": "Liquidity Analysis",
        "13.8": "Technical Analysis",
        "13.8.1": "Indicator Inputs",
        "13.8.2": "Indicator Rules",
        "13.9": "Fundamental Analysis",
        "13.10": "News Analysis",
        "13.10.1": "News Relevance",
        "13.10.2": "News Impact",
        "13.11": "Sentiment Analysis",
        "13.11.1": "Sentiment Inputs",
        "13.11.2": "Sentiment Confidence",
        "13.12": "Event Analysis",
        "13.13": "Macro-Economic Context",
        "13.14": "Sector Analysis",
        "13.15": "Asset-Level Analysis",
        "13.16": "Short-Term Signal Analysis",
        "13.17": "Conflicting Signal Detection",
        "13.17.1": "Conflict Identification",
        "13.17.2": "Conflict Resolution",
        "13.18": "Signal Confidence Assessment",
        "13.18.1": "Confidence Calculation",
        "13.18.2": "Confidence Threshold",
        "13.19": "Market Regime Detection",
        "13.19.1": "Regime Classification",
        "13.19.2": "Regime Transition",
        "13.20": "Historical Context Comparison",
        "13.21": "Real-Time Re-Analysis",
        "13.21.1": "Re-Analysis Trigger",
        "13.21.2": "Re-Analysis Frequency",
        "13.22": "Analysis Evidence Requirements",
        "13.23": "Analysis Explainability",
        "13.24": "Analysis Error Handling",
        "13.25": "Analysis Validation",
        "13.26": "Analysis Testing",
        "13.27": "Analysis Performance Metrics",
        "13.28": "Analysis Audit Trail",
        "13.29": "Analysis Acceptance Criteria",
        "13.30": "Analysis Change Control",
    },
    "14": {
        "14.1": "Scoring Objectives",
        "14.2": "Scoring Framework",
        "14.2.1": "Scoring Inputs",
        "14.2.2": "Scoring Formula",
        "14.3": "Return Potential Score",
        "14.4": "Risk Score",
        "14.5": "Risk-Reward Score",
        "14.6": "Probability Score",
        "14.7": "Liquidity Score",
        "14.8": "Volatility Score",
        "14.9": "Time-to-Opportunity Score",
        "14.10": "Data Confidence Score",
        "14.11": "Market Condition Score",
        "14.12": "News Impact Score",
        "14.13": "Cost and Fee Score",
        "14.14": "Tax Impact Score",
        "14.15": "Capital Requirement Score",
        "14.16": "Composite Opportunity Score",
        "14.16.1": "Component Scores",
        "14.16.2": "Composite Calculation",
        "14.17": "Score Weighting",
        "14.17.1": "Weight Definition",
        "14.17.2": "Weight Validation",
        "14.18": "Score Thresholds",
        "14.18.1": "Minimum Score",
        "14.18.2": "Rejection Threshold",
        "14.19": "Opportunity Ranking",
        "14.20": "Score Explainability",
        "14.21": "Score Recalculation",
        "14.21.1": "Recalculation Trigger",
        "14.22": "Score Decay",
        "14.22.1": "Score Decay Rule",
        "14.22.2": "Expiry Threshold",
        "14.23": "Score Validation",
        "14.24": "Score Sensitivity Testing",
        "14.25": "Scoring Error Detection",
        "14.26": "Scoring Performance Metrics",
        "14.27": "Scoring Audit Trail",
        "14.28": "Scoring Acceptance Criteria",
        "14.29": "Scoring Testing",
        "14.30": "Scoring Change Control",
    },
    "15": {
        "15.1": "Strategy Objectives",
        "15.2": "Strategy Definition",
        "15.2.1": "Strategy Definition Schema",
        "15.2.2": "Strategy Parameters",
        "15.3": "Strategy Eligibility",
        "15.4": "Entry Conditions",
        "15.4.1": "Entry Signal",
        "15.4.2": "Entry Validation",
        "15.5": "Exit Conditions",
        "15.5.1": "Exit Signal",
        "15.5.2": "Exit Validation",
        "15.6": "Position Sizing",
        "15.6.1": "Position Size Calculation",
        "15.6.2": "Position Size Limits",
        "15.7": "Capital Allocation",
        "15.7.1": "Allocation Rules",
        "15.7.2": "Allocation Limits",
        "15.8": "Holding Period Rules",
        "15.9": "Stop-Loss Rules",
        "15.9.1": "Stop-Loss Trigger",
        "15.9.2": "Stop-Loss Enforcement",
        "15.10": "Profit-Taking Rules",
        "15.10.1": "Profit Target",
        "15.10.2": "Profit-Taking Execution",
        "15.11": "Risk-Reward Requirements",
        "15.12": "Liquidity Requirements",
        "15.13": "Market Condition Requirements",
        "15.14": "Strategy Selection",
        "15.15": "Strategy Ranking",
        "15.16": "Strategy Parameterization",
        "15.17": "Strategy Constraints",
        "15.18": "Strategy Conflict Resolution",
        "15.18.1": "Conflict Detection",
        "15.18.2": "Strategy Priority",
        "15.19": "Strategy Backtesting Requirements",
        "15.20": "Strategy Simulation",
        "15.21": "Strategy Performance Metrics",
        "15.22": "Strategy Failure Detection",
        "15.23": "Strategy Validation",
        "15.24": "Strategy Explainability",
        "15.25": "Strategy Audit Trail",
        "15.26": "Strategy Re-Evaluation",
        "15.27": "Strategy Testing",
        "15.28": "Strategy Acceptance Criteria",
        "15.29": "Strategy Change Proposal",
        "15.30": "Strategy Change Control",
    },
    "16": {
        "16.1": "Risk Management Objectives",
        "16.2": "Capital Protection Principles",
        "16.3": "Maximum Capital Exposure",
        "16.3.1": "Exposure Calculation",
        "16.3.2": "Exposure Limit Enforcement",
        "16.4": "Maximum Position Exposure",
        "16.5": "Maximum Loss Limits",
        "16.5.1": "Per-Trade Loss Limit",
        "16.5.2": "Aggregate Loss Limit",
        "16.6": "Daily Loss Limits",
        "16.7": "Drawdown Limits",
        "16.7.1": "Drawdown Calculation",
        "16.7.2": "Drawdown Action",
        "16.8": "Stop-Loss Enforcement",
        "16.9": "Liquidity Risk Controls",
        "16.10": "Volatility Risk Controls",
        "16.11": "Market Risk Controls",
        "16.12": "Concentration Risk Controls",
        "16.13": "Counterparty Risk Controls",
        "16.14": "Data Risk Controls",
        "16.15": "Model Risk Controls",
        "16.16": "Execution Risk Controls",
        "16.17": "Fraud and Manipulation Detection",
        "16.18": "Kill Switch",
        "16.18.1": "Kill-Switch Triggers",
        "16.18.2": "Kill-Switch Actions",
        "16.18.3": "Kill-Switch Recovery",
        "16.19": "Emergency Stop",
        "16.19.1": "Emergency Conditions",
        "16.19.2": "Emergency State",
        "16.20": "Human Approval Gates",
        "16.20.1": "Approval-Required Actions",
        "16.20.2": "Approval Rejection and Timeout",
        "16.21": "Risk Escalation",
        "16.21.1": "Escalation Threshold",
        "16.21.2": "Escalation Path",
        "16.22": "Risk Monitoring",
        "16.23": "Risk Reporting",
        "16.24": "Risk Validation",
        "16.25": "Risk Testing",
        "16.26": "Risk Failure Handling",
        "16.27": "Risk Audit Trail",
        "16.28": "Risk Metrics",
        "16.29": "Risk Acceptance Criteria",
        "16.30": "Risk Change Control",
    },
    "17": {
        "17.1": "Backtesting Objectives",
        "17.2": "Historical Dataset Requirements",
        "17.2.1": "Dataset Selection",
        "17.2.2": "Dataset Quality",
        "17.3": "Simulation Environment",
        "17.4": "Historical Market Replay",
        "17.4.1": "Market Replay Rules",
        "17.4.2": "Time Ordering",
        "17.5": "Strategy Simulation",
        "17.6": "Entry",
        "17.7": "Exit",
        "17.8": "Position Sizing",
        "17.9": "Transaction Cost",
        "17.9.1": "Transaction Costs",
        "17.9.2": "Cost Assumptions",
        "17.10": "Brokerage Fee",
        "17.11": "Tax and Charge",
        "17.12": "Slippage",
        "17.12.1": "Slippage Model",
        "17.12.2": "Slippage Parameters",
        "17.13": "Liquidity",
        "17.14": "Market Impact",
        "17.15": "Multiple Market Conditions",
        "17.16": "Bull/Bear/Sideways Testing",
        "17.17": "Stress Testing",
        "17.18": "Edge-Case Testing",
        "17.19": "Out-of-Sample Testing",
        "17.19.1": "Training Period",
        "17.19.2": "Test Period",
        "17.20": "Walk-Forward Testing",
        "17.20.1": "Walk-Forward Windows",
        "17.21": "Overfitting Detection",
        "17.21.1": "Overfitting Indicators",
        "17.21.2": "Overfitting Decision",
        "17.22": "Performance Metrics",
        "17.23": "Risk Metrics",
        "17.24": "Benchmark Comparison",
        "17.25": "Simulation Reproducibility",
        "17.26": "Backtest Validation",
        "17.27": "Backtest Failure Handling",
        "17.28": "Backtest Audit Trail",
        "17.29": "Backtest Acceptance Criteria",
        "17.30": "Backtest Change Control",
    },
    "18": {
        "18.1": "Paper Trading Objectives",
        "18.2": "Virtual Capital Configuration",
        "18.2.1": "Initial Virtual Capital",
        "18.2.2": "Capital Reset Rules",
        "18.3": "Live Market Data Integration",
        "18.4": "Simulated Order Generation",
        "18.4.1": "Order Generation Conditions",
        "18.4.2": "Order Validation",
        "18.5": "Simulated Order Execution",
        "18.5.1": "Execution Model",
        "18.5.2": "Execution Failure",
        "18.6": "Slippage Simulation",
        "18.7": "Fee Simulation",
        "18.8": "Tax and Charge Simulation",
        "18.9": "Position Tracking",
        "18.10": "Cash Balance Tracking",
        "18.11": "Real-Time P&L",
        "18.11.1": "P&L Calculation",
        "18.11.2": "P&L Update Frequency",
        "18.12": "Unrealized P&L",
        "18.13": "Realized P&L",
        "18.14": "Performance Metrics",
        "18.15": "Risk Metrics",
        "18.16": "Strategy Performance",
        "18.17": "Execution Accuracy",
        "18.18": "Signal-to-Execution Tracking",
        "18.19": "Paper Trading Monitoring",
        "18.20": "Paper Trading Alerts",
        "18.21": "Paper Trading Failure Handling",
        "18.22": "Paper Trading Reconciliation",
        "18.22.1": "Position Reconciliation",
        "18.22.2": "Cash Reconciliation",
        "18.23": "Paper Trading Audit Trail",
        "18.24": "Paper Trading Validation",
        "18.25": "Paper Trading Testing",
        "18.26": "Paper Trading Acceptance Criteria",
        "18.27": "Paper Trading Duration Criteria",
        "18.28": "Paper-to-Live Readiness",
        "18.28.1": "Readiness Criteria",
        "18.28.2": "Human Approval for Transition",
        "18.29": "Paper Trading Review",
        "18.30": "Paper Trading Change Control",
    },
    "19": {
        "19.1": "Decision Engine Objectives",
        "19.2": "Decision Inputs",
        "19.2.1": "Required Inputs",
        "19.2.2": "Input Validation",
        "19.3": "Decision Preconditions",
        "19.3.1": "Preconditions",
        "19.3.2": "Failed Preconditions",
        "19.4": "Opportunity Eligibility",
        "19.5": "Strategy Eligibility",
        "19.6": "Risk Eligibility",
        "19.7": "Data Confidence Requirements",
        "19.8": "Decision Rules",
        "19.8.1": "Decision Rule Order",
        "19.8.2": "Rule Priority",
        "19.9": "Decision Thresholds",
        "19.10": "Decision Ranking",
        "19.11": "Decision Prioritization",
        "19.12": "Capital Allocation Decision",
        "19.12.1": "Allocation Eligibility",
        "19.12.2": "Allocation Limits",
        "19.13": "Entry Decision",
        "19.14": "Exit Decision",
        "19.15": "No-Action Decision",
        "19.16": "Decision Rejection Rules",
        "19.17": "Decision Expiry",
        "19.18": "Decision Re-Evaluation",
        "19.19": "Conflicting Decision Handling",
        "19.19.1": "Conflict Detection",
        "19.19.2": "Conflict Resolution",
        "19.20": "Human Approval Gate",
        "19.20.1": "Approval Trigger",
        "19.20.2": "Approval Timeout",
        "19.20.3": "Approval Rejection",
        "19.21": "Decision Explainability",
        "19.22": "Decision Evidence",
        "19.23": "Decision Audit Trail",
        "19.24": "Decision Validation",
        "19.25": "Decision Testing",
        "19.26": "Decision Failure Handling",
        "19.27": "Decision Performance Metrics",
        "19.28": "Decision Acceptance Criteria",
        "19.29": "Decision Review",
        "19.30": "Decision Change Control",
    },
    "20": {
        "20.1": "Monitoring Objectives",
        "20.2": "Real-Time Portfolio Monitoring",
        "20.3": "Capital Monitoring",
        "20.4": "Position Monitoring",
        "20.5": "Order Monitoring",
        "20.6": "Market Monitoring",
        "20.7": "Strategy Monitoring",
        "20.8": "Risk Monitoring",
        "20.9": "Real-Time P&L",
        "20.10": "Realized P&L",
        "20.11": "Unrealized P&L",
        "20.12": "Fees and Charges",
        "20.13": "Tax Impact",
        "20.14": "Net Return Calculation",
        "20.14.1": "Gross Return",
        "20.14.2": "Costs and Charges",
        "20.14.3": "Net Return",
        "20.15": "Drawdown Monitoring",
        "20.16": "Performance Attribution",
        "20.17": "Benchmark Comparison",
        "20.18": "Alert Thresholds",
        "20.18.1": "Alert Threshold Definition",
        "20.18.2": "Alert Trigger",
        "20.19": "Anomaly Detection",
        "20.20": "Monitoring Failure Handling",
        "20.21": "Monitoring Data Integrity",
        "20.22": "P&L Reconciliation",
        "20.22.1": "Position Reconciliation",
        "20.22.2": "Cash and P&L",
        "20.23": "Monitoring Audit Trail",
        "20.24": "Monitoring Dashboard Integration",
        "20.25": "Monitoring Testing",
        "20.26": "Monitoring Validation",
        "20.27": "Monitoring Performance Metrics",
        "20.28": "Monitoring Acceptance Criteria",
        "20.29": "Monitoring Review",
        "20.30": "Monitoring Change Control",
    },
    "21": {
        "21.1": "Dashboard Objectives",
        "21.2": "Dashboard Lifecycle",
        "21.3": "Agent Status View",
        "21.3.1": "Agent State",
        "21.3.2": "Agent Current Activity",
        "21.4": "Sub-Agent Status View",
        "21.4.1": "Sub-Agent State",
        "21.4.2": "Sub-Agent Progress",
        "21.5": "Current Task View",
        "21.6": "Progress Percentage",
        "21.6.1": "Progress Calculation",
        "21.6.2": "Progress Update",
        "21.7": "Task Queue View",
        "21.8": "Dependency Status",
        "21.9": "Blocked Task View",
        "21.9.1": "Blocker Details",
        "21.9.2": "Required Action",
        "21.10": "Error Status View",
        "21.11": "Data Source Status View",
        "21.12": "Market Analysis View",
        "21.13": "Opportunity View",
        "21.14": "Strategy View",
        "21.15": "Risk View",
        "21.16": "Portfolio View",
        "21.17": "P&L View",
        "21.18": "Decision View",
        "21.19": "Agent Activity Log",
        "21.20": "Audit Trail View",
        "21.21": "Human Approval Requests",
        "21.21.1": "Approval Request Details",
        "21.21.2": "Approval State",
        "21.22": "Notification Center",
        "21.23": "System Health View",
        "21.24": "Performance View",
        "21.25": "Historical Activity View",
        "21.26": "Search and Filtering",
        "21.27": "User Interaction",
        "21.27.1": "Allowed User Actions",
        "21.27.2": "Restricted Actions",
        "21.28": "Dashboard Security",
        "21.29": "Dashboard Testing",
        "21.30": "Dashboard Acceptance Criteria",
    },
    "22": {
        "22.1": "Human Interaction",
        "22.2": "Human-in-the-Loop",
        "22.3": "Approval Requirements",
        "22.3.1": "Approval Trigger",
        "22.3.2": "Approval Content",
        "22.3.3": "Approval Outcome",
        "22.4": "Clarification Requests",
        "22.4.1": "Clarification Trigger",
        "22.4.2": "Clarification Content",
        "22.5": "Escalation Requests",
        "22.5.1": "Escalation Trigger",
        "22.5.2": "Escalation Destination",
        "22.6": "Risk Alerts",
        "22.7": "Error Alerts",
        "22.8": "System Failure Alerts",
        "22.9": "Blocked Task Alerts",
        "22.10": "Performance Alerts",
        "22.11": "P&L Alerts",
        "22.12": "Security Alerts",
        "22.13": "Push Notifications",
        "22.14": "Email Notifications",
        "22.15": "Dashboard Notifications",
        "22.16": "Notification Priority",
        "22.16.1": "Priority Levels",
        "22.16.2": "Priority Assignment",
        "22.17": "Notification Routing",
        "22.18": "Notification Deduplication",
        "22.19": "Notification Acknowledgement",
        "22.20": "Notification Retry",
        "22.21": "Human Response Timeout",
        "22.22": "Escalation Chain",
        "22.23": "Workflow Non-Blocking Interaction",
        "22.23.1": "Non-Blocking Conditions",
        "22.23.2": "Blocking Conditions",
        "22.24": "Human Decision",
        "22.25": "Notification Testing",
        "22.26": "Notification Validation",
        "22.27": "Notification Security",
        "22.28": "Notification Audit Trail",
        "22.29": "Notification Acceptance Criteria",
        "22.30": "Notification Change Control",
    },
    "23": {
        "23.1": "Observability Objectives",
        "23.2": "Event Logging",
        "23.3": "Agent Activity Logging",
        "23.4": "Sub-Agent Activity Logging",
        "23.5": "Decision Logging",
        "23.6": "Data Acquisition Logging",
        "23.7": "Error Logging",
        "23.8": "Configuration Logging",
        "23.9": "SRS Change Logging",
        "23.10": "User Interaction Logging",
        "23.11": "Approval Logging",
        "23.12": "Deployment Logging",
        "23.13": "Performance Logging",
        "23.14": "Security Logging",
        "23.15": "Audit Event Structure",
        "23.15.1": "Mandatory Event Fields",
        "23.15.2": "Event Types",
        "23.16": "Event Timestamping",
        "23.17": "Event Correlation",
        "23.17.1": "Correlation Rules",
        "23.18": "Trace IDs",
        "23.18.1": "Trace ID Generation",
        "23.18.2": "Trace Propagation",
        "23.19": "Log Integrity",
        "23.19.1": "Integrity Protection",
        "23.19.2": "Tamper Detection",
        "23.20": "Log Retention",
        "23.20.1": "Retention Period",
        "23.20.2": "Secure Deletion",
        "23.21": "Observability Metrics",
        "23.22": "Health Monitoring",
        "23.23": "Distributed Tracing",
        "23.24": "Alerting",
        "23.25": "Audit Search",
        "23.26": "Audit Reporting",
        "23.27": "Observability Testing",
        "23.28": "Observability Validation",
        "23.29": "Audit Acceptance Criteria",
        "23.30": "Observability Change Control",
    },
    "24": {
        "24.1": "Error Management",
        "24.2": "Error Classification",
        "24.2.1": "Error Categories",
        "24.2.2": "Severity Classification",
        "24.3": "Input Errors",
        "24.4": "Data Errors",
        "24.5": "API Errors",
        "24.6": "Network Errors",
        "24.7": "Tool Errors",
        "24.8": "Agent Errors",
        "24.9": "Sub-Agent Errors",
        "24.10": "Logic Errors",
        "24.11": "Integration Errors",
        "24.12": "Security Errors",
        "24.13": "Runtime Errors",
        "24.14": "Error Detection",
        "24.15": "Error Severity Levels",
        "24.15.1": "Severity Levels",
        "24.15.2": "Severity-to-Action Mapping",
        "24.16": "Automatic Recovery",
        "24.16.1": "Recoverable Errors",
        "24.16.2": "Non-Recoverable Errors",
        "24.17": "Retry Policies",
        "24.17.1": "Retry Conditions",
        "24.17.2": "Retry Limits",
        "24.18": "Fallback Mechanisms",
        "24.18.1": "Fallback Selection",
        "24.18.2": "Fallback Failure",
        "24.19": "Safe-State Transition",
        "24.19.1": "Safe-State Definition",
        "24.19.2": "Safe-State Transition",
        "24.20": "Task Restart",
        "24.21": "Task Rollback",
        "24.22": "State Recovery",
        "24.23": "Error Escalation",
        "24.24": "Human Intervention",
        "24.25": "Error Root-Cause Analysis",
        "24.25.1": "Evidence Collection",
        "24.25.2": "Root-Cause Classification",
        "24.26": "Error Evidence Collection",
        "24.27": "Recovery Validation",
        "24.28": "Recovery Testing",
        "24.29": "Error Audit Trail",
        "24.30": "Error Recovery Change Control",
    },
    "25": {
        "25.1": "Self-Evaluation Objectives",
        "25.2": "Goal Compliance Check",
        "25.2.1": "Goal Checklist",
        "25.2.2": "Goal Deviation Test",
        "25.3": "SRS Compliance Check",
        "25.3.1": "SRS Coverage",
        "25.3.2": "SRS Violation Detection",
        "25.4": "Scope Compliance Check",
        "25.5": "Requirement Compliance Check",
        "25.6": "Technical Compliance Check",
        "25.7": "Data Quality Check",
        "25.8": "Agent Behaviour Check",
        "25.9": "Output Quality Check",
        "25.10": "Performance Evaluation",
        "25.11": "Accuracy Evaluation",
        "25.12": "Reliability Evaluation",
        "25.13": "Risk Evaluation",
        "25.14": "Security Evaluation",
        "25.15": "Dependency Evaluation",
        "25.16": "Integration Evaluation",
        "25.17": "Testing Evaluation",
        "25.18": "Documentation Evaluation",
        "25.19": "Progress Evaluation",
        "25.20": "Stuck-State Detection",
        "25.20.1": "Stuck-State Definition",
        "25.20.2": "Stuck-State Detection",
        "25.21": "Deviation Detection",
        "25.21.1": "Deviation Detection",
        "25.21.2": "Deviation Severity",
        "25.22": "Regression Detection",
        "25.23": "Evidence Collection",
        "25.24": "Evaluation Scoring",
        "25.24.1": "Evaluation Score Calculation",
        "25.24.2": "Score Threshold",
        "25.25": "Evaluation Thresholds",
        "25.26": "Failed Evaluation Handling",
        "25.26.1": "Recovery Action",
        "25.26.2": "Escalation Action",
        "25.27": "Self-Evaluation Reporting",
        "25.28": "Evaluation Audit Trail",
        "25.29": "Evaluation Acceptance Criteria",
        "25.30": "Evaluation Change Control",
    },
    "26": {
        "26.1": "Self-Improvement Objectives",
        "26.2": "Improvement Scope",
        "26.3": "Improvement Opportunity Detection",
        "26.3.1": "Improvement Trigger",
        "26.3.2": "Improvement Candidate",
        "26.4": "Issue Identification",
        "26.5": "Root-Cause Analysis",
        "26.5.1": "Root-Cause Evidence",
        "26.5.2": "Root-Cause Confidence",
        "26.6": "Improvement Proposal",
        "26.6.1": "Proposal Definition",
        "26.6.2": "Expected Benefit",
        "26.7": "Evidence Requirement",
        "26.8": "Impact Analysis",
        "26.8.1": "Functional Impact",
        "26.8.2": "Risk Impact",
        "26.9": "Risk Analysis",
        "26.10": "Regression Analysis",
        "26.11": "Proposed Code Changes",
        "26.12": "Proposed Configuration Changes",
        "26.13": "Proposed SRS Changes",
        "26.13.1": "SRS Change Proposal",
        "26.13.2": "SRS Impact Analysis",
        "26.14": "Human Approval Requirement",
        "26.14.1": "Approval Trigger",
        "26.14.2": "Approval Decision",
        "26.15": "Change Validation",
        "26.16": "Automated Testing",
        "26.17": "Integration Testing",
        "26.18": "Rollback Mechanism",
        "26.18.1": "Rollback Trigger",
        "26.18.2": "Rollback Procedure",
        "26.19": "Version Creation",
        "26.20": "Change Documentation",
        "26.21": "Change Deployment",
        "26.22": "Post-Deployment Validation",
        "26.23": "Improvement Performance Measurement",
        "26.24": "Improvement Failure Handling",
        "26.25": "Unauthorized Change Prevention",
        "26.25.1": "Unauthorized Change Detection",
        "26.26": "Goal Protection",
        "26.26.1": "Immutable Goal Protection",
        "26.27": "SRS Protection",
        "26.27.1": "SRS Baseline Protection",
        "26.28": "Improvement Audit Trail",
        "26.29": "Improvement Acceptance Criteria",
        "26.30": "Improvement Change Control",
    },
    "27": {
        "27.1": "SRS Governance Objectives",
        "27.2": "SRS Ownership",
        "27.3": "SRS Authority",
        "27.4": "SRS Structure",
        "27.5": "Version Numbering",
        "27.5.1": "Version Format",
        "27.5.2": "Version Increment",
        "27.6": "Baseline Definition",
        "27.7": "Baseline Locking",
        "27.8": "Change Request",
        "27.8.1": "Change Request Content",
        "27.9": "Change Proposal",
        "27.9.1": "Change Proposal",
        "27.9.2": "Change Justification",
        "27.10": "Change Impact Analysis",
        "27.10.1": "Impact Areas",
        "27.10.2": "Risk Assessment",
        "27.11": "Change Approval",
        "27.11.1": "Approval Authority",
        "27.11.2": "Approval State",
        "27.12": "Change Rejection",
        "27.13": "Emergency Change",
        "27.13.1": "Emergency Criteria",
        "27.13.2": "Emergency Approval",
        "27.14": "Version History",
        "27.15": "Change Log",
        "27.16": "Requirement Traceability",
        "27.17": "Document Integrity",
        "27.18": "Conflict Resolution",
        "27.19": "SRS Consistency Checks",
        "27.20": "SRS Validation",
        "27.21": "SRS Audit",
        "27.22": "SRS Access Control",
        "27.23": "SRS Backup",
        "27.24": "SRS Recovery",
        "27.25": "SRS Review Cycle",
        "27.26": "SRS Approval Workflow",
        "27.26.1": "Review",
        "27.26.2": "Approval",
        "27.27": "SRS Change Testing",
        "27.28": "SRS Release Management",
        "27.28.1": "Release Preparation",
        "27.28.2": "Release Validation",
        "27.29": "SRS Acceptance Criteria",
        "27.30": "SRS Governance Change Control",
    },
    "28": {
        "28.1": "Traceability Objectives",
        "28.2": "Requirement Identification",
        "28.3": "Requirement IDs",
        "28.3.1": "ID Format",
        "28.3.2": "ID Uniqueness",
        "28.4": "Requirement Classification",
        "28.5": "Requirement Source",
        "28.6": "Requirement-to-Goal Mapping",
        "28.7": "Requirement-to-SRS Mapping",
        "28.8": "Requirement-to-Task Mapping",
        "28.9": "Requirement-to-Agent Mapping",
        "28.10": "Requirement-to-Code Mapping",
        "28.10.1": "Requirement-to-Code Mapping",
        "28.10.2": "Code Coverage Status",
        "28.11": "Requirement-to-Test Mapping",
        "28.11.1": "Requirement-to-Test Mapping",
        "28.11.2": "Test Result Mapping",
        "28.12": "Requirement-to-Output Mapping",
        "28.13": "Dependency Traceability",
        "28.14": "Change Traceability",
        "28.15": "Decision Traceability",
        "28.16": "Evidence Traceability",
        "28.17": "Version Traceability",
        "28.18": "Coverage Measurement",
        "28.18.1": "Coverage Calculation",
        "28.18.2": "Coverage Threshold",
        "28.19": "Missing Trace Detection",
        "28.19.1": "Missing Trace Detection",
        "28.20": "Broken Trace Detection",
        "28.20.1": "Broken Trace Detection",
        "28.21": "Traceability Validation",
        "28.22": "Traceability Reporting",
        "28.23": "Traceability Audit",
        "28.24": "Traceability Testing",
        "28.25": "Traceability Acceptance Criteria",
    },
}

# Authorized lifecycle statuses for controlled documents (Topic 1.4/1.6).
REQ_AUTHORIZED_STATUSES: Final[frozenset[str]] = frozenset(
    {
        "DRAFT",
        "IN_REVIEW",
        "APPROVED",
        "BASELINED",
        "SUPERSEDED",
        "REJECTED",
        "ARCHIVED",
    }
)


def get_requirement_title(topic: str, requirement_id: str) -> str:
    """Return the title for a numbered requirement ID.

    Args:
        topic: Topic number as a string (e.g. ``"1"``).
        requirement_id: Numbered requirement ID (e.g. ``"1.3.2"``).

    Returns:
        The registered title for the requirement.

    Raises:
        KeyError: If the topic or requirement ID is not registered.
    """
    if topic not in REQ_REGISTRY:
        raise KeyError(f"Topic {topic} is not registered in the requirements registry")
    if requirement_id not in REQ_REGISTRY[topic]:
        raise KeyError(f"Requirement {requirement_id} is not registered in topic {topic}")
    return REQ_REGISTRY[topic][requirement_id]
